/*
* Ekconf, an Eclipe plug-in for configuring the Linux kernel or Buildroot.
* 
* Copyright (C) 2012 Tiana Rakotovao <rakotovaomahefa@gmail.com>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 52 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ekconf_internal_kconfig_NativeConfiguration */

#ifndef _Included_ekconf_internal_kconfig_NativeConfiguration
#define _Included_ekconf_internal_kconfig_NativeConfiguration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ekconf_internal_kconfig_NativeConfiguration
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ekconf_internal_kconfig_NativeConfiguration_nativeInit
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     ekconf_internal_kconfig_NativeConfiguration
 * Method:    nativeHasChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ekconf_internal_kconfig_NativeConfiguration_nativeHasChanged
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeConfiguration
 * Method:    nativeDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ekconf_internal_kconfig_NativeConfiguration_nativeDispose
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeConfiguration
 * Method:    nativeWriteConfiguration
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ekconf_internal_kconfig_NativeConfiguration_nativeWriteConfiguration
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ekconf_internal_kconfig_NativeConfiguration
 * Method:    nativefindMenu
 * Signature: (Ljava/lang/String;)[J
 */
JNIEXPORT jlongArray JNICALL Java_ekconf_internal_kconfig_NativeConfiguration_nativefindMenu
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ekconf_internal_kconfig_NativeConfiguration
 * Method:    nativeLoadAlternateConfiguration
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ekconf_internal_kconfig_NativeConfiguration_nativeLoadAlternateConfiguration
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
