/*
* Ekconf, an Eclipe plug-in for configuring the Linux kernel or Buildroot.
* 
* Copyright (C) 2012 Tiana Rakotovao Andriamahefa <rkmahefa@gmail.com>
* 
* This program is free software; you can redistribute it and/or
* modify it under the terms of the GNU General Public License
* as published by the Free Software Foundation; either version 2
* of the License, or (at your option) any later version.
* 
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
* 
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 52 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ekconf_internal_kconfig_NativeMenu */

#ifndef _Included_ekconf_internal_kconfig_NativeMenu
#define _Included_ekconf_internal_kconfig_NativeMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeGetpList
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeGetpList
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeGetpNext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeGetpNext
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeGetpSym
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeGetpSym
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeHasProperty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeHasProperty
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeGetPrompt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeGetPrompt
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeIsVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeIsVisible
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeGetHelp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeGetHelp
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    nativeGetPropertyType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ekconf_internal_kconfig_NativeMenu_nativeGetPropertyType
  (JNIEnv *, jobject);

/*
 * Class:     ekconf_internal_kconfig_NativeMenu
 * Method:    getpParent
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ekconf_internal_kconfig_NativeMenu_getpParent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
